version: '3'
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    container_name: sol_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_TCP_PORT}
    ports:
      - ${DB_PORT}
